// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1) {
  return window['go']['main']['App']['Ask'](arg1);
}

export function GetSelectedModel() {
  return window['go']['main']['App']['GetSelectedModel']();
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function T(arg1, arg2) {
  return window['go']['main']['App']['T'](arg1, arg2);
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}
