// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function Ask(arg1) {
  return window['go']['main']['App']['Ask'](arg1);
}

export function GetSelectedModel() {
  return window['go']['main']['App']['GetSelectedModel']();
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function T(arg1, arg2, arg3) {
  return window['go']['main']['App']['T'](arg1, arg2, arg3);
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}
