// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Ask(arg1:string):Promise<void>;

export function GetSelectedModel():Promise<main.ModelPresentation>;

export function NewConversation():Promise<void>;

export function RemoveFile(arg1:number):Promise<boolean>;

export function SelectFiles(arg1:string):Promise<void>;

export function T(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Translate(arg1:string):Promise<string>;
